### PR TITLE
Add multisig wallet support

### PR DESCRIPTION
**Pull request by Gusarich**
This pull request adds support of Multi-signature wallets.
The code is based on our repository [puppycats/multisig](https://github.com/puppycats/multisig), we just adapted the tests from Mocha & Chai to Jest.
If you think we should change something in code or structure, just tell what :)

We added three new exported classes: `MultisigWallet`, `MultisigOrder` and `MultisigOrderBuilder`
 - `MultisigWallet` is for interactions with Multisignature wallets
 - `MultisigOrderBuilder` is for creating orders and adding messages to them
 - `MultisigOrder` is for adding signatures to orders

Descriptions of functions are available in [README.md](https://github.com/puppycats/multisig#readme).
There's also an example of usage in src/examples.ts file

### CODE REVIEW

**Comment by Gusarich** [comment]
@ex3ndr can you please review it?

**Comment by Gusarich** [comment]
code style is fixed to be same as in other parts of the library. this PR is ready for merge now.

**Comment by Gusarich** [comment]
after talking with @dvlkv, we changed some functions and classes.

**Review by dvlkv — APPROVED** [review]
LGTM

**Pull request merged**
